// Code generated by go-swagger; DO NOT EDIT.

package segments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/lyuvolkova/avitoTest-dynSeg/tests/client/models"
)

// CreateSegmentReader is a Reader for the CreateSegment structure.
type CreateSegmentReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateSegmentReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateSegmentOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewCreateSegmentInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /segments] createSegment", response, response.Code())
	}
}

// NewCreateSegmentOK creates a CreateSegmentOK with default headers values
func NewCreateSegmentOK() *CreateSegmentOK {
	return &CreateSegmentOK{}
}

/*
CreateSegmentOK describes a response with status code 200, with default header values.

CreateSegmentOK create segment o k
*/
type CreateSegmentOK struct {
	Payload *models.CreateSegmentResponse
}

// IsSuccess returns true when this create segment o k response has a 2xx status code
func (o *CreateSegmentOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create segment o k response has a 3xx status code
func (o *CreateSegmentOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create segment o k response has a 4xx status code
func (o *CreateSegmentOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this create segment o k response has a 5xx status code
func (o *CreateSegmentOK) IsServerError() bool {
	return false
}

// IsCode returns true when this create segment o k response a status code equal to that given
func (o *CreateSegmentOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the create segment o k response
func (o *CreateSegmentOK) Code() int {
	return 200
}

func (o *CreateSegmentOK) Error() string {
	return fmt.Sprintf("[POST /segments][%d] createSegmentOK  %+v", 200, o.Payload)
}

func (o *CreateSegmentOK) String() string {
	return fmt.Sprintf("[POST /segments][%d] createSegmentOK  %+v", 200, o.Payload)
}

func (o *CreateSegmentOK) GetPayload() *models.CreateSegmentResponse {
	return o.Payload
}

func (o *CreateSegmentOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CreateSegmentResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateSegmentInternalServerError creates a CreateSegmentInternalServerError with default headers values
func NewCreateSegmentInternalServerError() *CreateSegmentInternalServerError {
	return &CreateSegmentInternalServerError{}
}

/*
CreateSegmentInternalServerError describes a response with status code 500, with default header values.

CreateSegmentInternalServerError create segment internal server error
*/
type CreateSegmentInternalServerError struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this create segment internal server error response has a 2xx status code
func (o *CreateSegmentInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create segment internal server error response has a 3xx status code
func (o *CreateSegmentInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create segment internal server error response has a 4xx status code
func (o *CreateSegmentInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this create segment internal server error response has a 5xx status code
func (o *CreateSegmentInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this create segment internal server error response a status code equal to that given
func (o *CreateSegmentInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the create segment internal server error response
func (o *CreateSegmentInternalServerError) Code() int {
	return 500
}

func (o *CreateSegmentInternalServerError) Error() string {
	return fmt.Sprintf("[POST /segments][%d] createSegmentInternalServerError  %+v", 500, o.Payload)
}

func (o *CreateSegmentInternalServerError) String() string {
	return fmt.Sprintf("[POST /segments][%d] createSegmentInternalServerError  %+v", 500, o.Payload)
}

func (o *CreateSegmentInternalServerError) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *CreateSegmentInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
