// Code generated by go-swagger; DO NOT EDIT.

package segments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/lyuvolkova/avitoTest-dynSeg/tests/client/models"
)

// DeleteSegmentReader is a Reader for the DeleteSegment structure.
type DeleteSegmentReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteSegmentReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteSegmentOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewDeleteSegmentInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /segments/{slug}] deleteSegment", response, response.Code())
	}
}

// NewDeleteSegmentOK creates a DeleteSegmentOK with default headers values
func NewDeleteSegmentOK() *DeleteSegmentOK {
	return &DeleteSegmentOK{}
}

/*
DeleteSegmentOK describes a response with status code 200, with default header values.

DeleteSegmentOK delete segment o k
*/
type DeleteSegmentOK struct {
	Payload *models.DeleteSegmentResponse
}

// IsSuccess returns true when this delete segment o k response has a 2xx status code
func (o *DeleteSegmentOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete segment o k response has a 3xx status code
func (o *DeleteSegmentOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete segment o k response has a 4xx status code
func (o *DeleteSegmentOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete segment o k response has a 5xx status code
func (o *DeleteSegmentOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete segment o k response a status code equal to that given
func (o *DeleteSegmentOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the delete segment o k response
func (o *DeleteSegmentOK) Code() int {
	return 200
}

func (o *DeleteSegmentOK) Error() string {
	return fmt.Sprintf("[DELETE /segments/{slug}][%d] deleteSegmentOK  %+v", 200, o.Payload)
}

func (o *DeleteSegmentOK) String() string {
	return fmt.Sprintf("[DELETE /segments/{slug}][%d] deleteSegmentOK  %+v", 200, o.Payload)
}

func (o *DeleteSegmentOK) GetPayload() *models.DeleteSegmentResponse {
	return o.Payload
}

func (o *DeleteSegmentOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DeleteSegmentResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteSegmentInternalServerError creates a DeleteSegmentInternalServerError with default headers values
func NewDeleteSegmentInternalServerError() *DeleteSegmentInternalServerError {
	return &DeleteSegmentInternalServerError{}
}

/*
DeleteSegmentInternalServerError describes a response with status code 500, with default header values.

DeleteSegmentInternalServerError delete segment internal server error
*/
type DeleteSegmentInternalServerError struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this delete segment internal server error response has a 2xx status code
func (o *DeleteSegmentInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete segment internal server error response has a 3xx status code
func (o *DeleteSegmentInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete segment internal server error response has a 4xx status code
func (o *DeleteSegmentInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete segment internal server error response has a 5xx status code
func (o *DeleteSegmentInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this delete segment internal server error response a status code equal to that given
func (o *DeleteSegmentInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the delete segment internal server error response
func (o *DeleteSegmentInternalServerError) Code() int {
	return 500
}

func (o *DeleteSegmentInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /segments/{slug}][%d] deleteSegmentInternalServerError  %+v", 500, o.Payload)
}

func (o *DeleteSegmentInternalServerError) String() string {
	return fmt.Sprintf("[DELETE /segments/{slug}][%d] deleteSegmentInternalServerError  %+v", 500, o.Payload)
}

func (o *DeleteSegmentInternalServerError) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *DeleteSegmentInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
