// Code generated by go-swagger; DO NOT EDIT.

package segments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new segments API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for segments API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	CreateSegment(params *CreateSegmentParams, opts ...ClientOption) (*CreateSegmentOK, error)

	DeleteSegment(params *DeleteSegmentParams, opts ...ClientOption) (*DeleteSegmentOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
CreateSegment Создает новый сегмент
*/
func (a *Client) CreateSegment(params *CreateSegmentParams, opts ...ClientOption) (*CreateSegmentOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCreateSegmentParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "createSegment",
		Method:             "POST",
		PathPattern:        "/segments",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &CreateSegmentReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*CreateSegmentOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for createSegment: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
DeleteSegment Удаляет сегмент
*/
func (a *Client) DeleteSegment(params *DeleteSegmentParams, opts ...ClientOption) (*DeleteSegmentOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDeleteSegmentParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "deleteSegment",
		Method:             "DELETE",
		PathPattern:        "/segments/{slug}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &DeleteSegmentReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DeleteSegmentOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for deleteSegment: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
