// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CreateSegmentRequest create segment request
//
// swagger:model CreateSegmentRequest
type CreateSegmentRequest struct {

	// slug
	// Example: avito_discount_90
	Slug string `json:"slug,omitempty"`
}

// Validate validates this create segment request
func (m *CreateSegmentRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this create segment request based on context it is used
func (m *CreateSegmentRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateSegmentRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateSegmentRequest) UnmarshalBinary(b []byte) error {
	var res CreateSegmentRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
