// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CreateSegmentResponse create segment response
//
// swagger:model CreateSegmentResponse
type CreateSegmentResponse struct {

	// ok
	Ok bool `json:"ok,omitempty"`
}

// Validate validates this create segment response
func (m *CreateSegmentResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this create segment response based on context it is used
func (m *CreateSegmentResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateSegmentResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateSegmentResponse) UnmarshalBinary(b []byte) error {
	var res CreateSegmentResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
