// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DeleteSegmentResponse delete segment response
//
// swagger:model DeleteSegmentResponse
type DeleteSegmentResponse struct {

	// ok
	Ok bool `json:"ok,omitempty"`
}

// Validate validates this delete segment response
func (m *DeleteSegmentResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this delete segment response based on context it is used
func (m *DeleteSegmentResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DeleteSegmentResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DeleteSegmentResponse) UnmarshalBinary(b []byte) error {
	var res DeleteSegmentResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
