// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetUserSegmentsResponse get user segments response
//
// swagger:model GetUserSegmentsResponse
type GetUserSegmentsResponse struct {

	// slugs
	// Example: ["avito_discount_70","avito_discount_50"]
	Slugs []string `json:"slugs"`
}

// Validate validates this get user segments response
func (m *GetUserSegmentsResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get user segments response based on context it is used
func (m *GetUserSegmentsResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GetUserSegmentsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetUserSegmentsResponse) UnmarshalBinary(b []byte) error {
	var res GetUserSegmentsResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
