// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UpdateUserSegmentsRequest update user segments request
//
// swagger:model UpdateUserSegmentsRequest
type UpdateUserSegmentsRequest struct {

	// добавляет пользователя в эти сегменты
	// Example: ["avito_discount_70","avito_discount_50"]
	AddSlug []string `json:"add_slug"`

	// удаляет пользователя из этих сегментов
	// Example: ["avito_discount_30"]
	DeleteSlug []string `json:"delete_slug"`
}

// Validate validates this update user segments request
func (m *UpdateUserSegmentsRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this update user segments request based on context it is used
func (m *UpdateUserSegmentsRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UpdateUserSegmentsRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UpdateUserSegmentsRequest) UnmarshalBinary(b []byte) error {
	var res UpdateUserSegmentsRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
