// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UpdateUserSegmentsResponse update user segments response
//
// swagger:model UpdateUserSegmentsResponse
type UpdateUserSegmentsResponse struct {

	// ok
	Ok bool `json:"ok,omitempty"`
}

// Validate validates this update user segments response
func (m *UpdateUserSegmentsResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this update user segments response based on context it is used
func (m *UpdateUserSegmentsResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UpdateUserSegmentsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UpdateUserSegmentsResponse) UnmarshalBinary(b []byte) error {
	var res UpdateUserSegmentsResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
