// Code generated by go-swagger; DO NOT EDIT.

package user_segments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/lyuvolkova/avitoTest-dynSeg/tests/client/models"
)

// GetUserSegmentsReader is a Reader for the GetUserSegments structure.
type GetUserSegmentsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetUserSegmentsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetUserSegmentsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetUserSegmentsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /users/{userID}/segments] getUserSegments", response, response.Code())
	}
}

// NewGetUserSegmentsOK creates a GetUserSegmentsOK with default headers values
func NewGetUserSegmentsOK() *GetUserSegmentsOK {
	return &GetUserSegmentsOK{}
}

/*
GetUserSegmentsOK describes a response with status code 200, with default header values.

GetUserSegmentsOK get user segments o k
*/
type GetUserSegmentsOK struct {
	Payload *models.GetUserSegmentsResponse
}

// IsSuccess returns true when this get user segments o k response has a 2xx status code
func (o *GetUserSegmentsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get user segments o k response has a 3xx status code
func (o *GetUserSegmentsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get user segments o k response has a 4xx status code
func (o *GetUserSegmentsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get user segments o k response has a 5xx status code
func (o *GetUserSegmentsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get user segments o k response a status code equal to that given
func (o *GetUserSegmentsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get user segments o k response
func (o *GetUserSegmentsOK) Code() int {
	return 200
}

func (o *GetUserSegmentsOK) Error() string {
	return fmt.Sprintf("[GET /users/{userID}/segments][%d] getUserSegmentsOK  %+v", 200, o.Payload)
}

func (o *GetUserSegmentsOK) String() string {
	return fmt.Sprintf("[GET /users/{userID}/segments][%d] getUserSegmentsOK  %+v", 200, o.Payload)
}

func (o *GetUserSegmentsOK) GetPayload() *models.GetUserSegmentsResponse {
	return o.Payload
}

func (o *GetUserSegmentsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetUserSegmentsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetUserSegmentsInternalServerError creates a GetUserSegmentsInternalServerError with default headers values
func NewGetUserSegmentsInternalServerError() *GetUserSegmentsInternalServerError {
	return &GetUserSegmentsInternalServerError{}
}

/*
GetUserSegmentsInternalServerError describes a response with status code 500, with default header values.

GetUserSegmentsInternalServerError get user segments internal server error
*/
type GetUserSegmentsInternalServerError struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this get user segments internal server error response has a 2xx status code
func (o *GetUserSegmentsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get user segments internal server error response has a 3xx status code
func (o *GetUserSegmentsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get user segments internal server error response has a 4xx status code
func (o *GetUserSegmentsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get user segments internal server error response has a 5xx status code
func (o *GetUserSegmentsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get user segments internal server error response a status code equal to that given
func (o *GetUserSegmentsInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get user segments internal server error response
func (o *GetUserSegmentsInternalServerError) Code() int {
	return 500
}

func (o *GetUserSegmentsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /users/{userID}/segments][%d] getUserSegmentsInternalServerError  %+v", 500, o.Payload)
}

func (o *GetUserSegmentsInternalServerError) String() string {
	return fmt.Sprintf("[GET /users/{userID}/segments][%d] getUserSegmentsInternalServerError  %+v", 500, o.Payload)
}

func (o *GetUserSegmentsInternalServerError) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *GetUserSegmentsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
