// Code generated by go-swagger; DO NOT EDIT.

package user_segments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetUserSegmentsParams creates a new GetUserSegmentsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetUserSegmentsParams() *GetUserSegmentsParams {
	return &GetUserSegmentsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetUserSegmentsParamsWithTimeout creates a new GetUserSegmentsParams object
// with the ability to set a timeout on a request.
func NewGetUserSegmentsParamsWithTimeout(timeout time.Duration) *GetUserSegmentsParams {
	return &GetUserSegmentsParams{
		timeout: timeout,
	}
}

// NewGetUserSegmentsParamsWithContext creates a new GetUserSegmentsParams object
// with the ability to set a context for a request.
func NewGetUserSegmentsParamsWithContext(ctx context.Context) *GetUserSegmentsParams {
	return &GetUserSegmentsParams{
		Context: ctx,
	}
}

// NewGetUserSegmentsParamsWithHTTPClient creates a new GetUserSegmentsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetUserSegmentsParamsWithHTTPClient(client *http.Client) *GetUserSegmentsParams {
	return &GetUserSegmentsParams{
		HTTPClient: client,
	}
}

/*
GetUserSegmentsParams contains all the parameters to send to the API endpoint

	for the get user segments operation.

	Typically these are written to a http.Request.
*/
type GetUserSegmentsParams struct {

	// UserID.
	//
	// Format: int64
	UserID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get user segments params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetUserSegmentsParams) WithDefaults() *GetUserSegmentsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get user segments params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetUserSegmentsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get user segments params
func (o *GetUserSegmentsParams) WithTimeout(timeout time.Duration) *GetUserSegmentsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get user segments params
func (o *GetUserSegmentsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get user segments params
func (o *GetUserSegmentsParams) WithContext(ctx context.Context) *GetUserSegmentsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get user segments params
func (o *GetUserSegmentsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get user segments params
func (o *GetUserSegmentsParams) WithHTTPClient(client *http.Client) *GetUserSegmentsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get user segments params
func (o *GetUserSegmentsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUserID adds the userID to the get user segments params
func (o *GetUserSegmentsParams) WithUserID(userID int64) *GetUserSegmentsParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the get user segments params
func (o *GetUserSegmentsParams) SetUserID(userID int64) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *GetUserSegmentsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param userID
	if err := r.SetPathParam("userID", swag.FormatInt64(o.UserID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
