// Code generated by go-swagger; DO NOT EDIT.

package user_segments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/lyuvolkova/avitoTest-dynSeg/tests/client/models"
)

// NewUpdateUserSegmentsParams creates a new UpdateUserSegmentsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateUserSegmentsParams() *UpdateUserSegmentsParams {
	return &UpdateUserSegmentsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateUserSegmentsParamsWithTimeout creates a new UpdateUserSegmentsParams object
// with the ability to set a timeout on a request.
func NewUpdateUserSegmentsParamsWithTimeout(timeout time.Duration) *UpdateUserSegmentsParams {
	return &UpdateUserSegmentsParams{
		timeout: timeout,
	}
}

// NewUpdateUserSegmentsParamsWithContext creates a new UpdateUserSegmentsParams object
// with the ability to set a context for a request.
func NewUpdateUserSegmentsParamsWithContext(ctx context.Context) *UpdateUserSegmentsParams {
	return &UpdateUserSegmentsParams{
		Context: ctx,
	}
}

// NewUpdateUserSegmentsParamsWithHTTPClient creates a new UpdateUserSegmentsParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateUserSegmentsParamsWithHTTPClient(client *http.Client) *UpdateUserSegmentsParams {
	return &UpdateUserSegmentsParams{
		HTTPClient: client,
	}
}

/*
UpdateUserSegmentsParams contains all the parameters to send to the API endpoint

	for the update user segments operation.

	Typically these are written to a http.Request.
*/
type UpdateUserSegmentsParams struct {

	// Body.
	Body *models.UpdateUserSegmentsRequest

	// UserID.
	//
	// Format: int64
	UserID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update user segments params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateUserSegmentsParams) WithDefaults() *UpdateUserSegmentsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update user segments params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateUserSegmentsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update user segments params
func (o *UpdateUserSegmentsParams) WithTimeout(timeout time.Duration) *UpdateUserSegmentsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update user segments params
func (o *UpdateUserSegmentsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update user segments params
func (o *UpdateUserSegmentsParams) WithContext(ctx context.Context) *UpdateUserSegmentsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update user segments params
func (o *UpdateUserSegmentsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update user segments params
func (o *UpdateUserSegmentsParams) WithHTTPClient(client *http.Client) *UpdateUserSegmentsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update user segments params
func (o *UpdateUserSegmentsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update user segments params
func (o *UpdateUserSegmentsParams) WithBody(body *models.UpdateUserSegmentsRequest) *UpdateUserSegmentsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update user segments params
func (o *UpdateUserSegmentsParams) SetBody(body *models.UpdateUserSegmentsRequest) {
	o.Body = body
}

// WithUserID adds the userID to the update user segments params
func (o *UpdateUserSegmentsParams) WithUserID(userID int64) *UpdateUserSegmentsParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the update user segments params
func (o *UpdateUserSegmentsParams) SetUserID(userID int64) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateUserSegmentsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param userID
	if err := r.SetPathParam("userID", swag.FormatInt64(o.UserID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
