// Code generated by go-swagger; DO NOT EDIT.

package user_segments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new user segments API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for user segments API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	GetUserSegments(params *GetUserSegmentsParams, opts ...ClientOption) (*GetUserSegmentsOK, error)

	UpdateUserSegments(params *UpdateUserSegmentsParams, opts ...ClientOption) (*UpdateUserSegmentsOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
GetUserSegments Возвращает сегменты, в которых состоит пользователь
*/
func (a *Client) GetUserSegments(params *GetUserSegmentsParams, opts ...ClientOption) (*GetUserSegmentsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetUserSegmentsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "getUserSegments",
		Method:             "GET",
		PathPattern:        "/users/{userID}/segments",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetUserSegmentsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetUserSegmentsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getUserSegments: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
UpdateUserSegments Обновляет сегменты у пользователя
*/
func (a *Client) UpdateUserSegments(params *UpdateUserSegmentsParams, opts ...ClientOption) (*UpdateUserSegmentsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewUpdateUserSegmentsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "updateUserSegments",
		Method:             "PATCH",
		PathPattern:        "/users/{userID}/segments",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &UpdateUserSegmentsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*UpdateUserSegmentsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for updateUserSegments: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
